apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: danyakladnitsky/lct-2024.backend:latest
          resources:
            limits:
              cpu: 800m
              memory: 768Mi
            requests:
              cpu: 400m
              memory: 512Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5