name: Push to Dockerhub

on:
  push:
    branches:
      - main

jobs:
  push-to-registry:
    name: Build and publish images to Docker Registry
    runs-on: self-hosted
    env:
      frontend: ${{secrets.DOCKERHUB_USERNAME}}/lct-2024.frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Push frontend image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{env.frontend}}:latest
          cache-from: type=registry,ref=${{env.frontend}}:${{github.sha}}
          cache-to: type=inline
          platforms: linux/x86_64